/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AcBacktop: typeof import('./../components/AcBacktop.vue')['default']
    AcCountDown: typeof import('./../components/AcCountDown.tsx')['default']
    AcIcon: typeof import('./../components/AcIcon.vue')['default']
    'AcIconEosIcons:threeDotsLoading': typeof import('~icons/eos-icons/three-dots-loading')['default']
    'AcIconEp:arrowDown': typeof import('~icons/ep/arrow-down')['default']
    'AcIconEp:questionFilled': typeof import('~icons/ep/question-filled')['default']
    AcIconEpArrowDown: typeof import('~icons/ep/arrow-down')['default']
    AcIconEpArrowLeftBold: typeof import('~icons/ep/arrow-left-bold')['default']
    AcIconEpArrowUpBold: typeof import('~icons/ep/arrow-up-bold')['default']
    AcIconEpDelete: typeof import('~icons/ep/delete')['default']
    AcIconEpEdit: typeof import('~icons/ep/edit')['default']
    AcIconEpLock: typeof import('~icons/ep/lock')['default']
    AcIconEpMoreFilled: typeof import('~icons/ep/more-filled')['default']
    AcIconEpPlus: typeof import('~icons/ep/plus')['default']
    AcIconEpSort: typeof import('~icons/ep/sort')['default']
    AcIconEpView: typeof import('~icons/ep/view')['default']
    'AcIconFe:plus': typeof import('~icons/fe/plus')['default']
    'AcIconIc:outlineFolder': typeof import('~icons/ic/outline-folder')['default']
    'AcIconMdi:star': typeof import('~icons/mdi/star')['default']
    'AcIconMdi:starOutline': typeof import('~icons/mdi/star-outline')['default']
    'AcIconPh:userCircleLight': typeof import('~icons/ph/user-circle-light')['default']
    AcIconUilFileBlank: typeof import('~icons/uil/file-blank')['default']
    AcLogo: typeof import('./../components/AcLogo.vue')['default']
    AcSelect: typeof import('./../components/AcSelect.vue')['default']
    AcSimpleTable: typeof import('./../components/AcSimpleTable.vue')['default']
    AcTransferTree: typeof import('./../components/AcTransferTree.vue')['default']
    AsyncMessageBox: typeof import('./../components/AsyncMessageBox.ts')['default']
    Avatar: typeof import('./../components/Avatar.vue')['default']
    ClipboardHelper: typeof import('./../components/ClipboardHelper.ts')['default']
    EmptyAvatar: typeof import('./../components/EmptyAvatar.vue')['default']
    Iconfont: typeof import('./../components/Iconfont.vue')['default']
    IconSvg: typeof import('./../components/IconSvg.vue')['default']
    Loading: typeof import('./../components/Loading.vue')['default']
    MenuItem: typeof import('./../components/MenuItem.vue')['default']
    MessagePage: typeof import('./../components/MessagePage.vue')['default']
    MessageTemplate: typeof import('./../components/MessageTemplate.vue')['default']
    PopperMenu: typeof import('./../components/PopperMenu.vue')['default']
    PromptTextarea: typeof import('./../components/PromptTextarea.vue')['default']
    Result: typeof import('./../components/Result.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Typings: typeof import('./../components/typings.ts')['default']
  }
}
