// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AcBacktop: typeof import('./src/components/AcBacktop.vue')['default']
    AcTable: typeof import('./src/components/AcTable.vue')['default']
    Feedback: typeof import('./src/components/Feedback/Feedback.vue')['default']
    ImageCorp: typeof import('./src/components/ImageCorp.vue')['default']
    ImagePreview: typeof import('./src/components/ImagePreview.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    ProjectExportModal: typeof import('./src/components/ProjectExportModal.vue')['default']
    ProjectShareModal: typeof import('./src/components/ProjectShareModal.vue')['default']
    Result: typeof import('./src/components/Result.vue')['default']
    SidebarMenu: typeof import('./src/components/SidebarMenu.vue')['default']
  }
}

export { }
